### ISSUE TITLE
Create Plutocracy demo notebook (TE Academy Fellowship Voting Example)

### ISSUE THREAD

**Issue by AngelaKTE** [TE-Academy/Reputation-based_Weighted_Voting#47]
#### Description

The \`plutocracy.py\`is a great resource for various metrics to measure to what extent "voting power whales" can control the voting.
All four metrics are great:

* Gini coefficient
* Thiel T + Thiel L
* Herfindahl-Hirschman Index (HHI)

#### Goal

I'd like to create a notebook that demo's these four metric using the actual TE Academy Fellowship voting data - before and after vote re-weighting.

In particular, it would be nice to see

* the Gini Coefficient (using a Lorenz Curve plot and wallets on the x-axis)
* HH Index with plotting the square chart

**Todos**

- [X] @akrtws to provide an anonymized .csv with wallets and NFTs (distribution by voting block)

[TE-Academy-NFTs_anonymized_block121859373.csv](https://uploads.linear.app/53fe8ba2-4864-46b3-b245-3bf76b17a5c0/6f831798-96f0-4173-9af5-aadd58f2b64e/2d7c4fb1-6f09-4027-ab65-0cf169a28a22?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzZmU4YmEyLTQ4NjQtNDZiMy1iMjQ1LTNiZjc2YjE3YTVjMC82ZjgzMTc5OC05NmYwLTQxNzMtOWFmNS1hYWRkNThmMmI2NGUvMmQ3YzRmYjEtNmYwOS00MDI3LWFiNjUtMGNmMTY5YTI4YTIyIiwiaWF0IjoxNzI1NTU3MTQzLCJleHAiOjMzMjk2MTE3MTQzfQ.1-Dzc_H_wmiR7D8mR0N4sa5Cf8_ZRmRcKvTxYQ3p7co)

- [ ] @eightarmsninebrains to add weights before/after re-weighting
- [ ] @eightarmsninebrains to calculate the [plutocracy.py](http://plutocracy.py) metrics and create charts
- [ ] @akrtws to integrate in write-up for final result

**Comment by eightarmsninebrains** [comment]
While this may be of interest specifically to TE Academy, I'd prefer to focus on the general explainers.

**Comment by eightarmsninebrains** [comment]
I propose we close this Issue as Completed. There are demonstrations of plutocracy metrics in the current `reweighting-techniques-demonstration.ipynb` notebook.

**Comment by AngelaKTE** [comment]
Out of scope for now.
